seed: 101
debug: False # set debug=False for Full Training
exp_name: 'new_Unet'
comment: 'new_Unet'
model_name: 'new_Unet'
train_bs: 4
valid_bs: 8
debug_train_bs: 10
debug_valid_bs: 10
img_size: [192, 192]
epochs: 50
lr: 0.00002
scheduler: 'CosineAnnealingLR'
min_lr: 0.00000000001
T_max: int(30000/train_bs*epochs)+50
T_0: 40
warmup_epochs: 0
wd: 0.000001
n_accumulate: max(1, 32//train_bs)
n_fold: 5
num_classes: 1
use_channel_attention : False
use_timestamp : False
use_DBM: False
attention: None
use_multimodal_data: True
lambda_ : 1
2.5D: False

