seed: 101
debug: False # set debug=False for Full Training
exp_name: 'SwinUnet'
comment: 'SwinUnet'
model_name: 'SwinUnet'
backbone: None
train_bs: 32
valid_bs: 32
debug_train_bs: 10
debug_valid_bs: 10
img_size: [320, 320]
epochs: 100
lr: 0.000001
scheduler: 'CosineAnnealingLR'
min_lr: 0.000001
T_max: int(30000/train_bs*epochs)+50
T_0: 40
warmup_epochs: 0
wd: 0.000001
n_accumulate: max(1, 32//train_bs)
n_fold: 5
num_classes: 3
use_channel_attention : False
use_timestamp : False
use_DBM: False
use_multimodal_data : False
attention: None
lambda_ : 2
2.5D: True

